//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseWorkEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class collegdeSexView
    {
        public string idGroup { get; set; }
        public Nullable<int> sexM { get; set; }
        public Nullable<int> sexF { get; set; }
        public Nullable<int> totalStudents { get; set; }
    }
}
