//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseWorkEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluations
    {
        public int idStudent { get; set; }
        public int idDisciplines { get; set; }
        public int numberSemester { get; set; }
        public int evaluation { get; set; }
        public Nullable<int> academicYear { get; set; }
    
        public virtual disciplines disciplines { get; set; }
        public virtual students students { get; set; }
    }
}
