//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseWorkEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int idHistory { get; set; }
        public int idStudent { get; set; }
        public System.DateTime dateReseption { get; set; }
        public Nullable<System.DateTime> dateLayoff { get; set; }
        public string idGroup { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual students students { get; set; }
    }
}
